# Generated by Django 6.0 on 2026-01-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='services',
            field=models.ManyToManyField(related_name='combos', to='barbershop.service'),
        ),
    ]
